name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: your_backend_image
        options: --privileged
        ports:
          - 8080:8080

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run PyRestTest
      run: |
        docker-compose up -d
        docker-compose run --rm backend ./tests.sh

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-selenium

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1

    - name: Run pytest-selenium tests
      run: |
        docker-compose up -d
        pytest tests_selenium
